From openjdk:8
copy ./build/libs/circuit-breaker-reading-application-0.0.1-SNAPSHOT.jar circuit-breaker-reading-application-0.0.1-SNAPSHOT.jar
CMD ["java","-jar","circuit-breaker-reading-application-0.0.1-SNAPSHOT.jar"]